-- 7월 아이스크림 총 주문량과 
-- 상반기의 아이스크림 총 주문량을 더한 값이 
-- 큰 순서대로 상위 3개의 맛을 조회

-- WITH ORDER_SUM AS(
--     SELECT FH.FLAVOR, FH.TOTAL_ORDER + JTO.JULY_ORDER AS TOTAL
--     FROM FIRST_HALF FH
--     JOIN (
--         SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
--         FROM JULY
--         GROUP BY FLAVOR
--     ) JTO
--         ON FH.FLAVOR = JTO.FLAVOR
--     ORDER BY TOTAL DESC
-- )

-- SELECT FLAVOR FROM ORDER_SUM LIMIT 3

SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (
    -- 아이스크림 별 7월 총 주문량
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) JO
    ON FH.FLAVOR = JO.FLAVOR
ORDER BY (FH.TOTAL_ORDER + JO.JULY_ORDER) DESC
LIMIT 3