SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT
    ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN ( 
    # PARENT_ITEM_ID가 ITEM_ID에 있다면 업그레이드 가능한 아이템
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE' # 업그레이드 가능한 아이템 중, 희귀도가 RARE인 것을 찾아달라고 했으므로, WHERE RARITY = 'RARE'로 검색
    )
ORDER BY II.ITEM_ID DESC