-- 케이스 1, 5 실패 -> ***길이가 NULL일 때 역시 10cm로 간주하여 평균을 구해야함
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) as MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE HAVING AVG(CASE WHEN LENGTH <= 10 THEN 10 ELSE LENGTH END) >= 33
ORDER BY FISH_TYPE ASC

-- 통과
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE HAVING AVG(CASE WHEN LENGTH <= 10 THEN 10 
                                   WHEN LENGTH IS NULL THEN 10 
                                   ELSE LENGTH 
                                   END ) >= 33
ORDER BY FISH_TYPE ASC 