-- 코드를 입력하세요
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)

-- 다른 방법 1
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, F1.PRICE
FROM  FOOD_PRODUCT F1 JOIN (SELECT MAX(PRICE) PRICE FROM FOOD_PRODUCT T) F2 
ON F1.PRICE = F2.PRICE

-- 다른 방법 2
WITH F2 AS (SELECT MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT)

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT JOIN F2
WHERE PRICE=F2.MAX_PRICE

-- 다른 방법 3 <<성능이 제일 좋다
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC LIMIT 1