-- 회원의 리뷰 조회
SELECT MEMBER_NAME
    , REVIEW_TEXT
    , DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
    ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID = (
    -- 리뷰 횟수가 가장 많은 회원
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1
    -- 집계함수는 ORDER BY절에도 사용 가능
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC