-- 보호소 들어올 당시에는 중성화되지 않았지만, 나갈 당시에는 중성화된 동물의 아이디, 생물 종, 이름

SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS OUTS
JOIN ANIMAL_INS INS
    ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE (INS.SEX_UPON_INTAKE LIKE "Intact%") AND (OUTS.SEX_UPON_OUTCOME LIKE "Spayed%" OR OUTS.SEX_UPON_OUTCOME LIKE "Neutered%")