SELECT BOOK.CATEGORY
    , SUM(BOOK_SUM) AS TOTAL_SALES
FROM BOOK
JOIN (
    -- 2022년 1월의 도서별 판매량을 합산하는 서브쿼리
    SELECT BOOK_ID
        , SUM(SALES) AS BOOK_SUM
    FROM BOOK_SALES
    -- 2022년 1월
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) SUM_SALES
    ON BOOK.BOOK_ID = SUM_SALES.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY CATEGORY