SELECT FI.ID
    , FNI.FISH_NAME
    , MAX_LENGTH.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN (
    -- 종류 별로 길이가 가장 큰 물고기를 조회하는 서브쿼리
    SELECT FISH_TYPE
        , MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_LENGTH
    ON FI.FISH_TYPE = MAX_LENGTH.FISH_TYPE
    AND FI.LENGTH = MAX_LENGTH.LENGTH
ORDER BY FI.ID