SELECT EMP.EMP_NO,
    EMP.EMP_NAME,
    CASE
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN AVG(SCORE) >= 96 THEN EMP.SAL * 0.2
        WHEN AVG(SCORE) >= 90 THEN EMP.SAL * 0.15
        WHEN AVG(SCORE) >= 80 THEN EMP.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_GRADE G
JOIN HR_EMPLOYEES EMP
    ON G.EMP_NO = EMP.EMP_NO
GROUP BY EMP.EMP_NO
ORDER BY EMP.EMP_NO ASC