-- CONCAT(문자열1, 문자열2, 문자열3, ...)
-- 여러 문자열을 하나로 합칠 수 있음

SELECT CONCAT('/home/grep/src/', BOARD.BOARD_ID, '/', FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_FILE FILE
    ON BOARD.BOARD_ID = FILE.BOARD_ID
WHERE BOARD.VIEWS = (
        SELECT MAX(VIEWS)
        FROM USED_GOODS_BOARD
)
ORDER BY FILE.FILE_ID DESC